#Codigo inicial
# name: CI Simple
# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout código
#         uses: actions/checkout@v3
#       - name: Ejecutar script
#         run: echo '¡Hola desde GitHub Actions!'

#ejecutable desde paso 5
name: CI con Shell
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Dar permisos de ejecución al script
        run: chmod +x script.sh

      - name: Ejecutar script Shell
        run: ./script.sh
